baseURL = 'https://ai-education.github.io'
languageCode = 'en-us'
title = 'AI Education Workshop'

enablerobotstxt = true
languagecode = "en-us"
paginate = 50
titlecasestyle = "Go"

[[module.imports]]
path = "github.com/willfaught/paige"

[languages.en]
weight = 10

[[languages.en.menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[languages.en.menu.main.params.paige]
disabled = true



[[languages.en.menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10


[[languages.en.menu.main]]
identifier = "topics"
name = "Focus topics"
url = "/topics/"
weight = 20

[[languages.en.menu.main]]
identifier = "schedule"
name = "Schedule"
url = "/schedule/"
weight = 30


[[languages.en.menu.main]]
identifier = "speakers"
name = "Speakers"
url = "/speakers/"
weight = 40


[[languages.en.menu.main]]
identifier = "location"
name = "Location"
url = "/location/"
weight = 50


[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[markup.tableofcontents]
endlevel = 6
ordered = true
startlevel = 2

[outputs]
home = ["atom", "html", "json", "rss"]
section = ["atom", "html", "rss"]
taxonomy = ["atom", "html", "rss"]
